In [1]:
import pandas as pd

In [2]:
wine_ds = pd.read_csv('data/WineDataset.csv')
wine_ds.head()

,Title,Description,Price,Capacity,Grape,Secondary Grape Varieties,Closure,Country,Unit,Characteristics,Per bottle / case / each,Type,ABV,Region,Style,Vintage,Appellation
0,"The Guv'nor, Spain",We asked some of our most prized winemakers wo...,£9.99 per bottle,75CL,Tempranillo,NaN,Natural Cork,Spain,10.5,"Vanilla, Blackberry, Blackcurrant",per bottle,Red,ABV 14.00%,NaN,Rich & Juicy,NV,NaN
1,Bread & Butter 'Winemaker's Selection' Chardon...,This really does what it says on the tin. It’s...,£15.99 per bottle,75CL,Chardonnay,NaN,Natural Cork,USA,10.1,"Vanilla, Almond, Coconut, Green Apple, Peach, ...",per bottle,White,ABV 13.50%,California,Rich & Toasty,2021,Napa Valley
2,"Oyster Bay Sauvignon Blanc 2022, Marlborough",Oyster Bay has been an award-winning gold-stan...,£12.49 per bottle,75CL,Sauvignon Blanc,NaN,Screwcap,New Zealand,9.8,"Tropical Fruit, Gooseberry, Grapefruit, Grass,...",per bottle,White,ABV 13.00%,Marlborough,Crisp & Zesty,2022,NaN
3,Louis Latour Mâcon-Lugny 2021/22,We’ve sold this wine for thirty years – and fo...,£17.99 per bottle,75CL,Chardonnay,NaN,Natural Cork,France,10.1,"Peach, Apricot, Floral, Lemon",per bottle,White,ABV 13.50%,Burgundy,Ripe & Rounded,2022,Macon
4,Bread & Butter 'Winemaker's Selection' Pinot N...,Bread & Butter is that thing that you can coun...,£15.99 per bottle,75CL,Pinot Noir,NaN,Natural Cork,USA,10.1,"Smoke, Black Cherry, Cedar, Raspberry, Red Fruit",per bottle,Red,ABV 13.50%,California,Smooth & Mellow,2021,Napa Valley

In [4]:
xwines = pd.read_csv('data/XWines_Slim_1K_wines.csv')
xwines.head()

,WineID,WineName,Type,Elaborate,Grapes,Harmonize,ABV,Body,Acidity,Code,Country,RegionID,RegionName,WineryID,WineryName,Website,Vintages
0,100001,Espumante Moscatel,Sparkling,Varietal/100%,['Muscat/Moscato'],"['Pork', 'Rich Fish', 'Shellfish']",7.5,Medium-bodied,High,BR,Brazil,1001,Serra Gaúcha,10001,Casa Perini,http://www.vinicolaperini.com.br,"[2020, 2019, 2018, 2017, 2016, 2015, 2014, 201..."
1,100002,Ancellotta,Red,Varietal/100%,['Ancellotta'],"['Beef', 'Barbecue', 'Codfish', 'Pasta', 'Pizz...",12.0,Medium-bodied,Medium,BR,Brazil,1001,Serra Gaúcha,10001,Casa Perini,http://www.vinicolaperini.com.br,"[2016, 2015, 2014, 2013, 2012, 2011, 2010, 200..."
2,100003,Cabernet Sauvignon,Red,Varietal/100%,['Cabernet Sauvignon'],"['Beef', 'Lamb', 'Poultry']",12.0,Full-bodied,High,BR,Brazil,1001,Serra Gaúcha,10002,Castellamare,https://www.emporiocastellamare.com.br,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."
3,100005,Maison de Ville Cabernet-Merlot,Red,Assemblage/Bordeaux Red Blend,"['Cabernet Sauvignon', 'Merlot']","['Beef', 'Lamb', 'Game Meat', 'Poultry']",11.0,Full-bodied,Medium,BR,Brazil,1001,Serra Gaúcha,10000,Aurora,http://www.vinicolaaurora.com.br,"[2021, 2020, 2019, 2018, 2017, 2016, 2015, 201..."
4,100007,Do Lugar Moscatel Espumantes,Sparkling,Varietal/100%,['Muscat/Moscato Bianco'],"['Pork', 'Rich Fish', 'Shellfish']",7.5,Medium-bodied,High,BR,Brazil,1001,Serra Gaúcha,10012,Dal Pizzol,http://www.dalpizzol.com.br,"[2018, 2017, 2016, 2015, 2014, 2013, 2012, 201..."

In [5]:
print(wine_ds.shape)
print(xwines.shape)

(1290, 17)
(1007, 17)

In [6]:
wine_ds_titles = set(wine_ds["Title"].values.tolist())
print(len(wine_ds_titles))

xwines_titles = set(xwines["WineName"].values.tolist())
print(len(xwines_titles))

1289
803

In [7]:
intersecting_names = wine_ds_titles.intersection(xwines_titles)
print(len(intersecting_names))

0

In [11]:
locations = pd.read_csv('data/europe2012ghd(Locations).csv', sep=';')
locations.head(10)

                   Location Latitude Longitude
0                    Alsace    48,17      7,28
1                  Auvergne    45,58      3,17
2            Auxerre-Avalon    47,78      3,57
3  Beaujolais and Maconnais    46,24      4,58
4                  Bordeaux    45,18     -0,75
5                  Burgundy    47,32      5,04
6              Champagne 1     49,04      3,97
7              Champagne 2     47,98      4,28
8       Gaillac- South-West     43,9       1,9
9                   Germany    48,77      9,17

In [14]:
regions = set(locations.Location.unique())
print(regions)

{'Vendée - Poitou Charente', 'Auxerre-Avalon', 'Savoie', 'Southern Lorraine', 'Champagne 1 ', 'Northern Italy', 'Maritime alps', 'Switzerland (Leman Lake)', 'Beaujolais and Maconnais', 'Languedoc', 'Bordeaux', 'Gaillac- South-West', 'Champagne 2 ', 'High Loire Valley', 'Alsace', nan, 'Southern Rhône valley', 'Germany', 'Ile de France', 'Luxembourg', 'Jura', 'Burgundy', 'Auvergne', 'Northern Lorraine', 'Northern Rhône valley', 'Various South-East', 'Spain', 'Low Loire Valley'}

In [15]:
wine_ds_regions = set(wine_ds["Region"].values.tolist())
wine_ds_regions

{'Abruzzo',
 'Aconcagua',
 'Alentejo',
 'Alsace',
 'Aragon',
 'Australia',
 'Austria',
 'Basilicata',
 'Beaujolais',
 'Bordeaux',
 'Bourgogne',
 'Bulgaria',
 'Burgundy',
 'California',
 'Campania',
 'Castilla Y León',
 'Castilla-La Mancha',
 'Catalunya',
 'Central Otago',
 'Central Valley',
 'Chile',
 'Coastal',
 'Constantia',
 'Corsica',
 'Dao',
 'Dordogne',
 'Douro',
 'Elgin',
 'Franschhoek',
 'Galicia',
 'Georgia',
 'Germany',
 'Gisborne',
 'Greece',
 'Hampshire',
 'Hawkes Bay',
 'Hungary',
 'Italy',
 'Jura & Savoie',
 'Kent',
 'Kvareli',
 'La Rioja',
 'Languedoc-Roussillon',
 'Le Marche',
 'Lebanon',
 'Limoux',
 'Lisboa',
 'Loire',
 'Lombardy',
 'Marlborough',
 'Martinborough',
 'Mendoza',
 'Moldova',
 'Nelson',
 'New South Wales',
 'North',
 'Oregon',
 'Other France',
 'Península De Setúbal',
 'Piedmont',
 'Prosecco Doc',
 'Prosecco Docg',
 'Provence',
 'Puglia',
 'Rhône',
 'Rioja And Navarra',
 'Robertson',
 'Romania',
 'San Juan',
 'Sardinia',
 'Serbia',
 'Sicily',
 'Slovenia',
 'South Australia',
 'South East Australia',
 'Stellenbosch',
 'Surrey',
 'Sussex',
 'Sw France (Ec. Boredeaux)',
 'Swartland',
 'Tasmania',
 'Tejo',
 'Trentino Alto Adige',
 'Tuscany',
 'Usa',
 'Valencia And Murcia',
 'Veneto',
 'Victoria',
 'Vinho Verde',
 'Waipara',
 'Walker Bay',
 'Washington State',
 'Western Australia',
 'Western Cape',
 nan}

In [16]:
xwines_regions = set(xwines["RegionName"].values.tolist())
xwines_regions

{'Abruzzo',
 'Adelaide Hills',
 'Ahr',
 'Alentejano',
 'Alentejo',
 'Alexander Valley',
 'Alsace',
 'Amador County',
 'Amarone della Valpolicella',
 'Amarone della Valpolicella Classico',
 'Amontillado Sherry',
 'Anapa (Анапа)',
 'Anderson Valley',
 'Arroyo Seco',
 'Asti',
 'Auckland',
 'Baden',
 'Bairrada',
 'Bandol',
 'Barbaresco',
 "Barbera d'Alba",
 "Barbera d'Asti",
 'Bardolino Classico',
 'Barolo',
 'Barossa Valley',
 'Beamsville Bench',
 'Beaujolais',
 'Beaujolais-Villages',
 'Beiras',
 'Bekaa Valley',
 'Bielersee',
 'Bierzo',
 'Bordeaux',
 'Bordeaux Supérieur',
 'Bourgogne',
 'Bourgogne Aligoté',
 "Brachetto d'Acqui",
 'Brauneberg',
 'Breede River Valley',
 'Brunello di Montalcino',
 'Burgenland',
 'Cabardès',
 'Cachapoal Valley',
 'Cafayate Valley',
 'Cahors',
 'California',
 'Calitzdorp',
 'Campanha Gaúcha',
 'Campo de Borja',
 'Canelones',
 'Canterbury',
 'Cape Agulhas',
 'Carignano del Sulcis',
 'Cariñena',
 'Carmelo',
 'Casablanca Valley',
 'Castilla',
 'Cava',
 'Central Coast',
 'Central Otago',
 'Central Valley (CL)',
 'Central Victoria',
 'Chablis',
 "Chablis 1er Cru 'Montmains'",
 'Chalkidiki',
 'Chambolle-Musigny',
 'Champagne',
 "Champagne Grand Cru 'Ambonnay'",
 "Champagne Grand Cru 'Bouzy'",
 "Champagne Grand Cru 'Le Mesnil-sur-Oger'",
 'Chianti',
 'Chianti Classico',
 'Chianti Colli Senesi',
 'Châteauneuf-du-Pape',
 'Clare Valley',
 'Colchagua Valley',
 'Collio',
 'Columbia Gorge Washington',
 'Columbia Valley',
 'Conegliano-Valdobbiadene Prosecco',
 'Conegliano-Valdobbiadene Prosecco Superiore Rive',
 'Continental Greece',
 'Coonawarra',
 'Corbières',
 'Corton-Charlemagne Grand Cru',
 'Costa Toscana',
 'Cream Sherry',
 'Crete',
 'Crimeia (Крим)',
 "Crémant d'Alsace",
 'Crémant de Bourgogne',
 'Crémant de Loire',
 'Cucamonga Valley',
 'Curico Valley',
 'Côtes de Bordeaux',
 'Côtes de Bourg',
 'Côtes de Gascogne',
 'Côtes de Provence',
 'Côtes-du-Rhône',
 'Dalmatian Coast',
 'Delle Venezie',
 "Dolcetto d'Alba",
 'Don Valley (Долина Дона)',
 'Douro',
 'Dry Creek Valley',
 'Dundee Hills',
 'Duriense',
 'Eger',
 'Elgin',
 'Elqui Valley',
 'Emilia-Romagna',
 'Ensenada',
 'Eola-Amity Hills',
 'Etna',
 'Fiano di Avellino',
 'Finger Lakes',
 'Fino Sherry',
 'Fleurie',
 'Francs-Côtes de Bordeaux',
 'Franken',
 'Frankland River',
 'Franschhoek',
 'Friuli-Venezia Giulia',
 'Fronsac',
 'Galilee',
 'Gavi',
 'Gevrey-Chambertin',
 'Gigondas',
 'Gimblett Gravels',
 'Gisborne',
 'Goriška Brda',
 'Grappa di Barbaresco',
 'Graves',
 'Greco di Tufo',
 'Happy Canyon of Santa Barbara',
 'Haut-Médoc',
 "Hawke's Bay",
 'Heathcote',
 'Horse Heaven Hills',
 'Hunter Valley',
 'Ilia',
 'Jerez-Xérès-Sherry',
 'Juanico',
 'Jumilla',
 'Jurançon',
 'Kamptal',
 'Kent',
 'Knights Valley',
 'Krania',
 'Langhe',
 'Languedoc-Roussillon',
 'Leyda Valley',
 'Limarí Valley',
 'Lisboa',
 'Listrac-Médoc',
 'Lodi',
 'Los Carneros',
 'Lujan de Cuyo',
 'Macedonia',
 'Madeirense',
 'Maipo Valley',
 'Maldonado',
 'Malta',
 'Marche',
 'Maremma Toscana',
 'Margaret River',
 'Margaux',
 'Marlborough',
 'Martinborough',
 'Maule Valley',
 'Mayschoss',
 'McLaren Vale',
 'Mendoza',
 'Mercurey',
 'Meursault',
 "Meursault 1er Cru 'La pièce sous le Bois'",
 'Minas Gerais',
 'Minho',
 'Mittelburgenland',
 'Moldova Viniculture',
 "Montepulciano d'Abruzzo",
 'Monterey County',
 'Montilla-Moriles',
 'Morava',
 'Morgon',
 'Mornington Peninsula',
 "Moscato d'Asti",
 'Mosel',
 'Moulis-en-Médoc',
 'Mount Veeder',
 'Murfatlar',
 'Méditerranée',
 'Nahe',
 'Napa Valley',
 'Navarra',
 'Neuchâtel',
 'Neusiedlersee',
 'New Mexico',
 'New South Wales',
 'Niagara Lakeshore',
 'Niagara Peninsula',
 'Niederösterreich',
 'North Coast',
 'North Island',
 'Nuits-Saint-Georges',
 'Oakville',
 'Odessa (Одеса)',
 'Okanagan Valley',
 'Ontario',
 'Orvieto',
 'Paarl',
 'Paso Robles',
 'Patagonia',
 'Pauillac',
 'Peloponnesos',
 'Pemberton',
 'Penedès',
 'Pessac-Léognan',
 'Petit Chablis',
 'Pfalz',
 'Piemonte',
 'Pomerol',
 'Pommard',
 'Porto',
 'Pouilly-Fuissé',
 'Pouilly-Fumé',
 'Primitivo di Manduria',
 'Priorat',
 'Prosecco',
 'Provence',
 'Puente Alto',
 'Puglia',
 'Querétaro',
 'Rapel Valley',
 'Recioto della Valpolicella Classico',
 'Red Mountain',
 'Rheingau',
 'Rheinhessen',
 'Rhone Valley',
 'Ribera del Duero',
 'Rio Grande do Sul',
 'Rioja',
 'Robertson',
 'Rosso di Montalcino',
 'Rubicone',
 'Rueda',
 'Russian River Valley',
 'Rutherford',
 'Rías Baixas',
 'Saint-Estèphe',
 'Saint-Julien',
 'Saint-Émilion Grand Cru',
 'Salento',
 'San José',
 'San Juan',
 'San Rafael',
 'Sancerre',
 'Santa Barbara County',
 'Santenay',
 'Santiago',
 'Santorini',
 'Sauternes',
 'Serra Gaúcha',
 'Serra Negra',
 'Slanghoek',
 'Slopes of Meliton',
 'Sonoma Coast',
 'Sonoma County',
 'Sonoma Valley',
 'South Australia',
 'South Eastern Australia',
 'South West Australia',
 'Southeastern Anatolia',
 'Stags Leap District',
 'Steiermark',
 'Stellenbosch',
 'Swan Hill',
 'Swartland',
 'Südsteiermark',
 'Südtirol-Alto Adige',
 'Taman Peninsula (Таманский полуостров)',
 'Temecula Valley',
 'Texas',
 'Tokaj',
 'Toscana',
 'Transylvania',
 'Trentino',
 'Trento',
 'Tupungato',
 'Uco Valley',
 'Upper Loire',
 'Vacqueyras',
 'Valais',
 'Valdadige',
 'Valdepeñas',
 'Vale do São Francisco',
 'Vale dos Vinhedos',
 "Valle d'Aosta",
 'Valle de Guadalupe',
 'Valpolicella',
 'Valpolicella Classico',
 'Valpolicella Ripasso',
 'Valtellina',
 'Veneto',
 'Villány',
 'Vin Santo del Chianti Classico',
 'Vin de France',
 'Vinemount Ridge',
 'Vinho Verde',
 'Vinho de Portugal',
 "Vino d'Italia",
 'Vino de España',
 'Virginia',
 'Wachau',
 'Wagram',
 'Waiheke Island',
 'Washington',
 'Western Cape',
 'Willamette Valley',
 'Wisconsin',
 'Württemberg',
 'Yarra Valley',
 'Yountville',
 'Zakarpattia (Закарпатська)'}

In [18]:
xwines_regions = set(xwines["Vintages"].values.tolist())
xwines_regions

{"['N.V.']",
 "[2010, 'N.V.']",
 '[2012, 2009, 2008, 2005, 2000, 1998, 1997, 1995, 1991, 1990, 1988, 1987, 1982, 1980, 1979, 1976, 1975, 1970, 1969, 1966]',
 '[2015, 2014, 2013, 2010, 2009, 2008, 2007]',
 '[2016, 2012, 2010, 2009, 2008, 2007, 2006]',
 '[2016, 2014, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004]',
 '[2016, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1985]',
 '[2016, 2015, 2011, 2005, 2003, 1999, 1997, 1995, 1994, 1993, 1990, 1989]',
 '[2016, 2015, 2014, 2013, 2012, 2011, 2007, 2002, 2000, 1985, 1980, 1976, 1970]',
 '[2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2001]',
 "[2017, 2016, 2015, 2014, 2009, 2004, 'N.V.']",
 '[2017, 2016, 2015, 2014, 2013, 2012, 2010, 2009, 2008, 2000, 1997, 1994, 1992, 1987]',
 '[2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2005]',
 '[2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2005, 1997]',
 '[2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2000, 1999, 1991, 1989, 1977, 1974, 1972, 1971]',
 "[2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2000, 1999, 1998, 1997, 1994, 1991, 1990, 1988, 1985, 1983, 1981, 1980, 1978, 1975, 1974, 1973, 1972, 1971, 1970, 1969, 1968, 1950, 'N.V.']",
 '[2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1993, 1982, 1970]',
 '[2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1995, 1994, 1985, 1978, 1959]',
 '[2017, 2016, 2015]',
 '[2018, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2005, 2004, 2003, 2001, 2000]',
 '[2018, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008]',
 '[2018, 2016, 2015, 2014, 2013, 2012, 2011, 2010]',
 '[2018, 2016, 2015, 2014, 2013, 2012, 2011]',
 '[2018, 2017, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2001, 2000, 1990]',
 '[2018, 2017, 2016, 2013, 2010, 2008, 2007, 2006, 2000]',
 '[2018, 2017, 2016, 2015, 2013, 2012, 2011, 2009, 2007, 2006]',
 '[2018, 2017, 2016, 2015, 2013]',
 '[2018, 2017, 2016, 2015, 2014, 2012, 2011, 2009, 2004, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1991, 1990, 1989, 1988, 1986, 1985, 1983, 1982, 1981, 1980, 1979, 1978, 1977, 1976, 1975, 1970]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2010, 2009, 2005, 2004, 2003, 2002, 2001, 1999, 1998, 1997, 1996]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2005]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2007, 2001, 1992, 1979, 1965, 1959]',
 "[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2003, 2000, 1981, 'N.V.']",
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2005]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2000, 1991, 1990]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2003, 2002, 2001, 1996, 1995, 1993, 1991, 1971]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2003, 2002]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 1967]',
 "[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2002, 2000, 1999, 1998, 1997, 1996, 1995, 1993, 1991, 1990, 1989, 1987, 1951, 'N.V.']",
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2002, 2001, 2000, 1999, 1996, 1991, 1990, 1986]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 1983]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1998, 1980]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1981, 1970]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1995, 1994, 1993, 1992, 1990, 1989, 1988]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1992, 1991, 1990, 1989, 1988]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1986, 1985, 1983, 1982, 1981, 1980, 1979, 1978, 1977, 1974, 1973, 1971, 1965, 1962, 1960, 1959, 1956]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1990, 1989, 1988, 1986, 1985, 1983, 1982]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1986, 1985, 1983, 1982, 1980, 1979, 1978, 1976, 1975, 1974, 1973, 1971, 1970, 1966, 1955]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000]',
 '[2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008]',
 '[2018, 2017, 2016, 2015]',
 "[2019, 2016, 2015, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2004, 2003, 2002, 2000, 1999, 1997, 1995, 1979, 1977, 'N.V.']",
 '[2019, 2017, 2016, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1994]',
 '[2019, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2008]',
 '[2019, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2006, 2002, 2000]',
 '[2019, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1991]',
 '[2019, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1986, 1983, 1982, 1980, 1974]',
 '[2019, 2018, 2015, 2013, 2012, 2010, 2009, 2007, 2005, 2004, 2002, 2001, 2000, 1991, 1989, 1983, 1979, 1978, 1977]',
 '[2019, 2018, 2017, 2014, 2013]',
 '[2019, 2018, 2017, 2016, 2000]',
 '[2019, 2018, 2017, 2016, 2015, 2011, 2001]',
 '[2019, 2018, 2017, 2016, 2015, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2001]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2011, 2010]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2007]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2010, 2008, 2006, 2005, 2004, 2000]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2011, 2009, 2008, 2007, 2005, 2004, 2002, 2000, 1999, 1998, 1997, 1995, 1992, 1991]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 1995]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2009, 2008, 2006, 1986, 1961]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2010]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2001]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2008, 2005, 2004, 1985]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2008, 2006]',
 "[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2008, 2007, 2006, 2005, 2004, 2003, 2001, 2000, 1999, 1994, 1993, 1990, 1988, 1987, 1984, 1981, 1977, 1968, 'N.V.']",
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2005, 2004]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2006, 2001, 2000]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2007, 2006, 2001, 2000, 1999, 1993, 1989, 1985, 1981, 1980, 1979, 1971, 1955]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2007, 2006, 2005, 2003]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2001, 1979]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2001]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2006, 1990]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2006, 2003, 2001, 2000, 1995, 1990, 1971]',
 "[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2006, 2004, 2003, 2001, 2000, 1999, 1997, 1996, 1994, 1993, 1990, 1988, 1987, 1986, 1985, 1983, 1982, 1981, 1980, 1979, 1978, 1975, 1973, 1972, 1971, 1968, 1967, 1966, 1965, 1963, 1962, 1958, 1955, 'N.V.']",
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2001, 1991, 1989, 1960]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2003, 2001, 1999, 1997, 1996, 1993, 1990, 1988, 1987, 1983, 1975]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2005, 2004, 2002, 2001, 2000, 1998, 1996, 1995, 1994]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2003, 1998, 1971]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2000]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2002, 2000]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2003, 1990]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2002, 2000, 1999, 1998, 1996, 1990, 1985]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1989, 1988, 1984, 1981]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2001, 1988]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2001, 2000]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2001]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 1999, 1981]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2000, 1999, 1997, 1996, 1995, 1993, 1982, 1968]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 1999, 1998, 1997, 1996, 1995, 1991, 1989, 1985]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1995, 1990, 1978]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1997, 1994, 1987, 1986]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1994, 1993, 1982]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1993, 1992, 1991, 1990, 1988, 1985, 1982, 1972, 1971, 1970, 1969, 1967]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1988, 1977]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1990, 1989, 1988, 1987, 1986, 1985, 1983, 1982, 1980, 1975, 1964, 1959]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1991]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1982, 1981]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1987, 1984, 1982, 1978, 1977, 1974, 1971, 1970, 1969, 1968, 1967, 1962, 1960]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1981, 1980]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1983]',
 "[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1986, 1985, 1981, 1980, 1960, 1959, 1950, 'N.V.']",
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1985, 1978, 1976, 1970, 1968, 1952]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1986, 1985, 1981, 1979, 1977, 1961, 1960]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1986, 1985, 1983, 1982, 1981, 1979, 1978, 1977, 1976, 1975, 1973, 1972, 1971, 1970, 1969, 1967, 1966, 1964, 1962, 1961, 1959, 1955, 1953, 1952]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1986, 1985, 1984, 1983, 1982, 1980, 1979, 1978, 1977, 1976, 1974, 1973, 1972, 1969, 1964]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1986, 1985, 1984, 1983, 1982, 1981, 1980, 1978, 1975, 1972, 1970, 1969, 1966, 1964]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000]',
 '[2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004]',
 '[2019, 2018, 2017, 2016]',
 '[2020, 2017, 2014, 2013, 2011, 2010, 2009, 2008, 2004, 2003, 2002, 2001, 1999, 1996, 1991]',
 '[2020, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2005, 1993]',
 '[2020, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2000, 1992]',
 '[2020, 2018, 2015, 2014, 2013, 2011, 2010, 2008, 2006, 2001, 2000]',
 '[2020, 2018, 2017, 2016, 2015, 2011, 2002, 2001, 2000, 1999, 1998, 1994, 1990, 1988, 1987]',
 '[2020, 2018, 2017, 2016, 2015, 2014, 2013, 2011]',
 '[2020, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2009, 2008, 2007, 2005]',
 '[2020, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1997, 1996, 1995, 1994, 1993, 1981]',
 '[2020, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2001, 2000, 1989]',
 '[2020, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 1999, 1997, 1996, 1995, 1994, 1993, 1992, 1990, 1986]',
 '[2020, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1995, 1990, 1988]',
 '[2020, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1994, 1993, 1992, 1991, 1967, 1966, 1953]',
 '[2020, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1986, 1985, 1984, 1983, 1982, 1980, 1976, 1969]',
 '[2020, 2019, 2016, 2015, 2014, 2013, 2012, 2010, 2008]',
 '[2020, 2019, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1985]',
 '[2020, 2019, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1990, 1989, 1988, 1987, 1986, 1985, 1983, 1982, 1981, 1978, 1976, 1975, 1973, 1967, 1964, 1962, 1961]',
 '[2020, 2019, 2017]',
 '[2020, 2019, 2018, 2001]',
 '[2020, 2019, 2018, 2016, 2014, 2008]',
 '[2020, 2019, 2018, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2002, 2001]',
 "[2020, 2019, 2018, 2017, 2015, 2014, 2012, 2011, 2009, 1995, 'N.V.']",
 '[2020, 2019, 2018, 2017, 2016, 2010, 2008, 2004]',
 '[2020, 2019, 2018, 2017, 2016, 2014, 2013, 2012]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 1991]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2006]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2010]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2013, 2011, 2010, 2007]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2013, 2012, 2011, 2010, 2009, 2008, 2006, 2005, 2001, 2000]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2011, 2010]',
 "[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2012, 2011, 2010, 'N.V.']",
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 1999]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2005]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2010]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2011, 2010, 2009, 2007, 2006]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2011, 2010, 2009]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2011, 2010]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2011]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2008, 2001, 1993]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2008, 2006]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2010, 2000]',
 "[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2010, 2005, 1999, 1997, 1989, 'N.V.']",
 "[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2010, 2009, 2008, 2006, 2005, 2003, 1997, 1992, 1988, 1987, 1986, 1985, 1984, 1983, 1981, 1979, 'N.V.']",
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2010, 2009]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2001]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2006, 2002]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2007, 1995]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2009, 2008, 2000]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2009]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2000]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2001, 2000]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2001]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2002]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2007, 2001, 2000]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2007, 2004, 2001, 2000]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2007, 2005, 2004, 2001]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2007, 2005]',
 '[2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2007, 2006, 2002, 2001, 2000]',